<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
         http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>


    <!-- =====================================================
         PROJECT INFORMATION
    ====================================================== -->

    <groupId>org.giritechhub</groupId>

    <artifactId>
        student-management-course-enrollment-system
    </artifactId>

    <version>0.0.1-SNAPSHOT</version>

    <packaging>war</packaging>


    <!-- =====================================================
         DEPENDENCIES
    ====================================================== -->

    <dependencies>


        <!-- =================================================
             SPRING MVC
        ================================================== -->

        <dependency>

            <groupId>org.springframework</groupId>

            <artifactId>spring-webmvc</artifactId>

            <version>6.2.11</version>

        </dependency>


        <!-- =================================================
             SPRING JDBC
        ================================================== -->

        <dependency>

            <groupId>org.springframework</groupId>

            <artifactId>spring-jdbc</artifactId>

            <version>6.2.11</version>

        </dependency>


        <!-- =================================================
             MYSQL JDBC DRIVER
        ================================================== -->

        <dependency>

            <groupId>com.mysql</groupId>

            <artifactId>mysql-connector-j</artifactId>

            <version>9.4.0</version>

        </dependency>


        <!-- =================================================
             JAKARTA SERVLET API
        ================================================== -->

        <dependency>

            <groupId>jakarta.servlet</groupId>

            <artifactId>jakarta.servlet-api</artifactId>

            <version>6.1.0</version>

            <scope>provided</scope>

        </dependency>


        <!-- =================================================
             JAKARTA JSP API
        ================================================== -->

        <dependency>

            <groupId>jakarta.servlet.jsp</groupId>

            <artifactId>jakarta.servlet.jsp-api</artifactId>

            <version>4.0.0</version>

            <scope>provided</scope>

        </dependency>


        <!-- =================================================
             JAKARTA JSTL API
        ================================================== -->

        <dependency>

            <groupId>jakarta.servlet.jsp.jstl</groupId>

            <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>

            <version>3.0.2</version>

        </dependency>


        <!-- =================================================
             JAKARTA JSTL IMPLEMENTATION
        ================================================== -->

        <dependency>

            <groupId>org.glassfish.web</groupId>

            <artifactId>jakarta.servlet.jsp.jstl</artifactId>

            <version>3.0.1</version>

        </dependency>
        
        <dependency>
    <groupId>org.springframework.security</groupId>
    <artifactId>spring-security-crypto</artifactId>
    <version>6.5.5</version>
</dependency>


    </dependencies>


    <!-- =====================================================
         BUILD CONFIGURATION
    ====================================================== -->

    <build>

        <plugins>


            <!-- =================================================
                 JAVA 21 COMPILER
            ================================================== -->

            <plugin>

                <groupId>org.apache.maven.plugins</groupId>

                <artifactId>maven-compiler-plugin</artifactId>

                <version>3.13.0</version>

                <configuration>

                    <release>21</release>

                </configuration>

            </plugin>


            <!-- =================================================
                 WAR PACKAGING
            ================================================== -->

            <plugin>

                <groupId>org.apache.maven.plugins</groupId>

                <artifactId>maven-war-plugin</artifactId>

                <version>3.4.0</version>

            </plugin>


        </plugins>

    </build>

</project>